#!/usr/bin/bash

#change these 3 lines to match your specific setup
GH_USER="baltic_website/baltic-gallery"
PC_USER="xtorrm"
POST_PATH="/mnt/c/Users/${PC_USER}/Documents/${GH_USER}/_posts" # update path when needed
IMG_PATH="/mnt/c/Users/${PC_USER}/Documents/${GH_USER}/assets/img"
FILE_NAME="$1"
CURR_DIR=`pwd`
FILE_BASE=`basename $FILE_NAME .ipynb`

POSTHTML_NAME="${FILE_BASE}.html"
POST_DATE_NAME=`date "+%Y-%m-%d-"`${POSTHTML_NAME}

# get header file
HEADER_FILE="${CURR_DIR}/header.txt"

# create html version of the file
jupyter nbconvert --to html $FILE_NAME --template lab

# add header to html file
cat $HEADER_FILE $POSTHTML_NAME > "${POST_DATE_NAME}"

# move everything to blog area
mv $POST_DATE_NAME ${POST_PATH}
