name: baltic - gallery
description: 'A gallery of visualisations made with baltic'
# permalink: ':title/'
permalink: /:title/
baseurl: "/baltic-gallery" # the subpath of your site, e.g. /blog
site-twitter: twitter.com/evogytis
logo: 'assets/img/logo.png' # change for something you would use. This is from the gallery website


include: ["_pages","_posts"]

# Author Settings
author: baltic developments # add your name
social-twitter: evogytis# add your Twitter handle
social-github: phylo-baltic # add your Github handle
# social-email: # add

# Defaults - gallery
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      
  # all pages - gallery
  - scope:
      path: "_pages"
    values:
      layout: page

# Tracker
analytics: # Google Analytics

# Pagination
paginate: 20

# Build Settings
markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-feed
  - jekyll-seo-tag

paginate: 8
paginate_path: "/page/:num"

exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]
